version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: tasks-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-todo_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasks-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-todo_db}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-network
    restart: unless-stopped
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge